### PR TITLE
Update GBA loader + proc.py for IDA Pro 9.3

### PR DESCRIPTION
**Pull request by laqieer**
Makes the repo work on **IDA Pro 9.3** (the loader previously broke on 9.x).

## Real breakages (Python only)
- **`loaders/GBA_Loader.py`** — the namesake loader:
  - `idaapi.cvar.inf.startIP/beginEA = …` → `ida_ida.inf_set_start_ip/start_ea(…)`. In IDA 9.x `idaapi.cvar.inf` is no longer writable like this and is **`None` under headless idalib**, so the old form raised `'NoneType' object has no attribute 'startIP'`. The setters work in both the GUI and idalib.
  - `Warning(…)` → `ida_kernwin.warning(…)`. The old IDC `Warning` global is gone from the Python namespace; a bare `Warning(…)` now resolves to Python's built-in exception class and silently no-ops.
- **`fe/scripts/proc.py`** — `MakeFunction(func)` → `add_func(func)` (`MakeFunction` was removed from the Python `idc` module).

## Left unchanged on purpose
The `.idc` scripts (`idc/*.idc`, `plugins/*.idc`) still run on IDA 9.3 through IDA's `idc.idc` backward-compatibility aliases (`Byte`, `MakeName`, `Message`, `MakeFunction`, … are all still defined in `<ida>/idc/idc.idc`), so they need no changes.

## Verified
Loaded a GBA ROM headlessly with **idalib on IDA 9.3**: processor set to ARM, all 8 segments (BIOS/WRAM/IRAM/IO/OBJ/VRAM/OAM/ROM) created, entry `start` named, `open_database` returns OK.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by laqieer** [comment]
## Copilot CLI review — findings resolved

Copilot reviewed this PR and correctly caught that the first commit's claim "`proc.py` is fixed for IDA 9.x" was **incomplete** — `proc.py` still failed to import on IDA 9.x's Python 3. Resolved in b84fdda:

1. **`print "…"` statements (lines 57, 123)** — Python-2 print statement → hard `SyntaxError` on Python 3. → `print(…)`.
2. **`find_binary(ea, SEARCH_DOWN, "…")` (line 62)** — `idc.find_binary` was removed in IDA 9.x. → `find_bytes("…", ea)` (verified the new `find_bytes(bs, range_start, …)` signature).
3. **`(end - ea) / 8` (line 70)** — Python-3 `/` is float division; `make_array` needs an int count. → `// 8`.
4. **`GetString(...)` (line 112)** — `idc.GetString` was removed. → `get_strlit_contents(...)` (returns `bytes`, now `.decode()`d).

Verification:
- `proc.py` now compiles under Python 3 (`python3 -c "compile(...)"` passes); `python/ida_gba.py` was already clean.
- The `.idc` scripts remain unchanged — confirmed they still run on IDA 9.3 via the `idc.idc` backward-compat aliases.
- Loader still verified end-to-end on IDA 9.3 idalib (8 segments + entry, OK).

Re-requesting a review on the updated branch.
